name: Latest youtube videos
on:
  schedule:
    - cron: '10 * * * *'
  workflow_dispatch:
jobs:
  update-readme-with-youtube:
    name: Update repo with latest videos
    runs-on: ubuntu-latest
    steps:
      - uses: gautamkrishnar/blog-post-workflow@master
        with:
          comment_tag_name: YOUTUBE
          feed_list: "https://www.youtube.com/feeds/videos.xml?channel_id=UC7-pjRSGoNEMoIujwOH2Mhw"
          readme_path: ./TEMPLATE.md
